const mongoose = require('../db/mongoose').mongoose
const ingredientSchema = mongoose.Schema({
    title:{
        type: String,
        required:true,
        maxlength:50
    },
    description:{
        type:String,
        maxlength:255
    },
    amount:{
        type:Number,
        required:true
    },
    unit: {
        type: String,
        required:true,
        enum : ['TEASPOON','TABLESPOON','FLUID_OUNCE','GILL','CUP','SPOONS','PINT','QUART','GALLON','MILLILITER','LITER','POUND','OUNCE','MILLIGRAM','GRAM','GRAMS','KILOGRAM','PCS',
        'G','TABLESPOONS','none','ML','OZJAR','CUPS','TBSP','TSP','BULB','RD','CLOVE','GCAN',
        'CLOVES','TIN','LEAVES','OZ','LB','SMALL','TEASPOONS','BUNCH','MLMILK','TBLSP','POT',
        'GSOAKEDOVERNIGHTINWATER','KGCUTINTO3CMCUBES','SKINNED','LARGE','SPRIGS',
        'CMPIECEFINELYCHOPPED','CLOVESPEELEDANDCHOPPED','GPEELEDANDCHOPPED','MEDIUM','SMALLPEELEDANDCOARSELYGRATED','TBSPCHOPPED',
        'CUTINTO1','LARGEPEELEDANDCHOPPED','TRIMMEDANDROUGHLYCHOPPED','TSPLIGHTLYTOASTEDANDTHENGENTLYCRUSHED','GTINNED',
        'GCUTINHALFLENGTHWAYS','GROUGHLYCRUMBLEDINTO0','RINSEDANDPATTEDDRY','GTORN','TBLS','CHOPPED','TSPGROUND','CAN','TBS',
        'TBSCHOPPED','TSPSHREDDED','THINSLICES','FREE','MLBOILING','SCOOP','CUPRAW','CUPBOILING','KG','THINLYSLICED',
        'FINELYCHOPPED','CLOVESCHOPPED','TSPDRIED','BONELESS','HEADCHOPPED','RED','CUPGRATED','OUNCES','FINELYSLICED','GPEELEDRAW',
        'GGRATED','GPIECE','SLICES','BEATEN','THINCUT','SLICEDTHINLY','WHOLE','THINPIECE','JUICE','SKINNLESS','TABLESPOONCHOPPED',
        'QUARTERED','BASHEDTOBREAKSHELLS','KGCUBED','DRIED','INCH','MARBLESIZED','MEATYSHANKS','MEDIUMCHOPPEDINTO','CHOPPEDINTO',
        'BULBCHOPPEDINTO','STRIPS','CUPCHOPPEDWITHJUICE','TABLESPOONSCHOPPED','TEASPOONMINCED','TEASPOONGRATED',
        'STALKCHOPPED','TABLESPOONMINCED','FRESHSPRIG','POUNDCHOPPED','THICKSLICES','SPRIG','MASHED','QUARTSNEUTRALFRYING','GNEW',
        'GBONELESS','FRESHKAFFIRLEAVES','STICKS','SMALLCUTINTOCHUNKS','SMALLSTALKS','MEDIUMFINELYDICED','MEDIUMCLOVESSLICED',
        'CUPSHALVED','PACKET','DICED','SMALLFINELYDICED','FINELYDICED','CLOVESMINCED','FILLETS','SLICED','SHREDDED','X300ML',
        'CLOVEFINELYCHOPPED','POUNDEDTO1CMTHICKNESS','GFINE','MLFRYING','CHOPPEDCLOVES','MLCAN','JUICEOF1','TBSPGRATED','LITREHOT','GLARGE',
        'GTIPSBLANCHEDBRIEFLYINBOILINGWATER','GSHAVINGS','FLORETS','ANCHO','X400G','X400GTINS','GSTEWINGCUTINTOSTRIPS','GWAXY',
        'CUTTHINWEDGES','TBSPPALMORSOFTLIGHT','REDDESEEDEDANDFINELYSLICED','POUNDSSLICED','PACKAGETHIN','TABLESPOONSMINCED',
        'TABLESPOONSMINCEDGARLIC','SLICESSQUARE','SLICESMILD','BOTTLE','GRAMSBONELESSSKIN','RASHERS','PINCHES','TAIL',
        'KNOB','MEDIUMCHOPPED','STICK','CLOVEPEELEDCRUSHED','HANDFULS','JAR','GCANS','TUBS','HANDFUL','PARTS','PART','GSHREDDED','GPACK',
        'SMALLCUTCHUNKS','TBLSPCHOPPED','SLICE','L','KNOBS','PODS','QT','CLOVESSLICED','TBSMINCED','LBS','POUNDS','PINCH','BAG','YOLKES',
        'LITRE','CLOVESCRUSHED','LARGECHOPPED','HEAD','DROPS','YOLK','DASH','CANS','NONE'],// needs to change acoording to the app
        default: 'pieces'
    },
    priority:{
        type:Number,
        min:1,
        required:true,
        

    },
    owner: {
        type: mongoose.Schema.Types.ObjectId,
        required: true,
        ref: 'Recipe'
    }
})
ingredientSchema.index({priority:1,owner:1},{unique:true})
ingredientSchema.index({title:1,description:1,owner:1},{unique:true})
const Ingridient = mongoose.model('Ingridient', ingredientSchema)
module.exports = Ingridient